version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - app_network

      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 

networks:
  app_network:
    driver: bridge